name       : double-conversion
version    : 3.1.5
release    : 1
source     :
    - https://github.com/google/double-conversion/archive/v3.1.5.tar.gz : a63ecb93182134ba4293fd5f22d6e08ca417caafa244afaa751cbfddf6415b13
license    : BSD-3-Clause
component  : programming.library
summary    : Efficient binary-decimal and decimal-binary conversion routines for IEEE doubles.
description: |
    Efficient binary-decimal and decimal-binary conversion routines for IEEE doubles. 
setup      : |
    %cmake -DBUILD_SHARED_LIBS=ON
build      : |
    %make
install    : |
    %make_install
